config/routes.rb
Rails.application.routes.draw do
  resources :donuts
  root 'donuts#home'

end

app/models/donut.rb
class Donut < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/donuts_controller.rb
class DonutsController < ApplicationController
  before_action :set_donut, only: [:show, :edit, :update, :destroy]

  def home
  end
  
  # GET /donuts
  # GET /donuts.json
  def index
    @donuts = Donut.all
  end

  # GET /donuts/1
  # GET /donuts/1.json
  def show
  end

  # GET /donuts/new
  def new
    @donut = Donut.new
  end

  # GET /donuts/1/edit
  def edit
  end

  # POST /donuts
  # POST /donuts.json
  def create
    @donut = Donut.new(donut_params)

    respond_to do |format|
      if @donut.save
        format.html { redirect_to @donut, notice: 'Donut was successfully created.' }
        format.json { render :show, status: :created, location: @donut }
      else
        format.html { render :new }
        format.json { render json: @donut.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /donuts/1
  # PATCH/PUT /donuts/1.json
  def update
    respond_to do |format|
      if @donut.update(donut_params)
        format.html { redirect_to @donut, notice: 'Donut was successfully updated.' }
        format.json { render :show, status: :ok, location: @donut }
      else
        format.html { render :edit }
        format.json { render json: @donut.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donuts/1
  # DELETE /donuts/1.json
  def destroy
    @donut.destroy
    respond_to do |format|
      format.html { redirect_to donuts_url, notice: 'Donut was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_donut
      @donut = Donut.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def donut_params
      params.require(:donut).permit(:name, :description, :price, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/donuts_helper.rb
module DonutsHelper
end

app/views/donuts/_form.html.erb
<%= form_for(@donut) do |f| %>
  <% if @donut.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@donut.errors.count, "error") %> prohibited this donut from being saved:</h2>

      <ul>
      <% @donut.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :price %><br>
    <%= f.number_field :price, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.text_field :image, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/donuts/edit.html.erb
<h1>Edit Donut</h1>

<%= render 'form' %>

app/views/donuts/home.html.erb
<div class="header">
	<%= image_tag "http://static.tumblr.com/f2444bae6687c57b88dcd476ac611f5f/iokgscd/EcNn30zzv/tumblr_static_wf-donuts-1.jpg", class: "img-responsive" %>
	<h1>HAHAHA This is my Shop NOWW!</h1>
</div>

<div class="buttons">
	<%= link_to "Check out our Donuts!", donuts_path, class: "btn btn-primary donut-link" %>
</div>

<p>This is my new feature!</p>

app/views/donuts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Donut Menu</h1>

<div class="row">
    <% @donuts.each do |donut| %>
        <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <%= image_tag donut.image, class: "img-responsive" %>
                <div class="caption">
                    <h3><%= donut.name %></h3>
                    <h4>$<%= donut.price %></h4>
                    <%= link_to "More Info", donut, class: "btn btn-default" %>
                </div>
            </div>
        </div>
    <% end %>
</div>

<div class="buttons">
    <%= link_to 'New Donut', new_donut_path, class: "btn btn-primary" %>
</div>

app/views/donuts/new.html.erb
<h1>New Donut</h1>

<%= render 'form' %>

app/views/donuts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="well">
	<legend>
		<h1><%= @donut.name %></h1>
	</legend>
  
	<%= image_tag @donut.image, class: "img-responsive" %>

	<h4>$<%= @donut.price %></h4>

	<p>
	  <%= @donut.description %>
	</p>
</div>




<div class="buttons">
	<%= link_to 'Edit', edit_donut_path(@donut), class: "btn btn-warning" %>  <%= link_to 'Delete', @donut, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>  <%= link_to 'Back to Menu', donuts_path, class: "btn btn-primary" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <title>DonutShop</title>

  <%= stylesheet_link_tag "//netdna.bootstrapcdn.com/bootswatch/3.0.2/journal/bootstrap.min.css" %>
  <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Shadows+Into+Light+Two" %>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <%= javascript_include_tag "//netdna.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.min.js" %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to Rails.application.class.parent_name, root_url, :class => "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Menu", donuts_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </nav>

  <div class="container">
    <% if notice.present? %>
      <div class="alert alert-dismissable alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= notice %>
      </div>
    <% end %>
    
    <div class="container">
      <%= yield %>
    </div>
    
  </div>
</body>
</html>